"""create_job_and_report_tables

Revision ID: 843b988b5e47
Revises: dd978d37882b
Create Date: 2026-09-02 22:11:41.424594

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "843b988b5e47"
down_revision: str | Sequence[str] | None = "dd978d37882b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("job_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status", sa.String(length=50), server_default="queued", nullable=False
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("report_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(op.f("ix_job_owner_id"), "job", ["owner_id"], unique=False)
    op.create_index(op.f("ix_job_status"), "job", ["status"], unique=False)
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["job.job_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report")
    op.drop_index(op.f("ix_job_status"), table_name="job")
    op.drop_index(op.f("ix_job_owner_id"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
